[config]
schemaVersion = "0.0.1"

[package]
namespace = "adamantSpeedrun"
name = "Surface_Rebalance"
description = "Surface-specific route and encounter rebalance options for the Speedrun modpack."
versionNumber = "2.0.0"
websiteUrl = "https://github.com/h2pack-speedrun/adamantSpeedrun-Surface_Rebalance"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.78"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-ModUtil = "4.0.1"
adamant-ModpackLib = "1.1.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

[publish]
repository = "https://thunderstore.io"
communities = ["hades-ii"]

[publish.categories]
hades-ii = ["mods"]
